name: Build
on:
  push:
    branches: '*'

jobs:
  build:

    strategy:
      matrix:
        node-version: [16.x]

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm test
